/* =====================================================================
   VOCABULARY — closed by design. Cross-time comparison only works if
   the same experience gets the same label every time.
   ===================================================================== */
const SIGNALS = {
  autonomy:{en:{s:'I had no choice',n:'Autonomy',g:'Something changed before you had a say in it.',
    p:'Next time someone changes your plan without asking, you may feel irritated before you know how much work it makes.',
    t:'You may not mind extra work as much as having no say in it.',t1:'extra work',t2:'having no say in it',
    a:'Or it may be unexpected change itself, not the say in it.',q:'What changes when you are asked first?'},
   zh:{s:'我没有选择',n:'自主权',g:'事情在你参与决定之前，就已经被改变了。',
    p:'下次如果有人没先问你就改了安排，你可能在还没弄清要多做多少之前，就已经开始烦了。',
    t:'你可能并不是讨厌工作变多，而是更在意没让你参与决定。',t1:'工作变多',t2:'这件事没有让你参与决定',
    a:'也可能真正让你不舒服的，只是变化本身来得突然。',q:'当有人先问过你的时候，有什么不一样？'}},
  heard:{en:{s:'I wasn’t heard',n:'Being heard',g:'You said something and it went past without landing.',
    p:'Next time you raise something and the room moves on, you may go quiet rather than say it twice.',
    t:'You may mind being unheard more than being disagreed with.',t1:'being disagreed with',t2:'not being heard',
    a:'Or it may be about the setting making it costly to repeat yourself.',q:'What happens when someone does pick it up?'},
   zh:{s:'没人听我说',n:'被听见',g:'你说了一句话，但它没落地就过去了。',
    p:'下次你提了一件事、话题却直接往下走，你可能会安静下来，而不是再说一遍。',
    t:'比起被反对，你可能更在意的是没有被听见。',t1:'被反对',t2:'没有被听见',
    a:'也可能是那个场合让「再说一遍」的代价太高。',q:'如果有人真的接住了你说的话，会怎么样？'}},
  fairness:{en:{s:'It wasn’t fair',n:'Fairness',g:'A rule seemed to apply to you and not to someone else.',
    p:'Next time an exception is made for someone else, it may bother you longer than the cost of it does.',
    t:'You may care less about the loss than about it being uneven.',t1:'the loss itself',t2:'it being uneven',
    a:'Or it may be about not knowing why the decision went that way.',q:'What would make it feel even?'},
   zh:{s:'不公平',n:'公平',g:'同一条规则，好像对你成立，对别人不成立。',
    p:'下次如果有人被特殊对待，那种不公平感可能比实际损失留得更久。',
    t:'比起损失本身，你可能更在意它不均等。',t1:'损失本身',t2:'它不均等',
    a:'也可能你卡住的是——没人说清为什么这么决定。',q:'要怎样才会觉得这件事是均等的？'}},
  standards:{en:{s:'Below my standard',n:'Standards',g:'Something went out below the bar you hold.',
    p:'Next time work ships rougher than you like, you may take it on yourself rather than name it.',
    t:'You may mind the drop in standard more than the hours it costs to fix.',t1:'the hours it costs to fix',t2:'the drop in standard',
    a:'Or it may be about who ends up carrying the fix.',q:'Whose standard is it, and who agreed to it?'},
   zh:{s:'达不到我的标准',n:'标准',g:'有东西以低于你标准的状态交了出去。',
    p:'下次如果东西做得比你希望的粗糙，你可能会自己接过来做，而不是把问题说出来。',
    t:'比起补救花的时间，你可能更在意标准掉下来了。',t1:'补救花掉的时间',t2:'标准掉了下来',
    a:'也可能真正的问题是——最后总由谁收拾。',q:'那条线是谁定的，有人同意过吗？'}},
  valued:{en:{s:'It went unnoticed',n:'Being seen',g:'Work you put effort into passed without being noticed.',
    p:'Next time effort goes unremarked, you may play it down out loud while it keeps bothering you.',
    t:'You may mind going unnoticed more than being criticised.',t1:'being criticised',t2:'going unnoticed',
    a:'Or it may be not knowing whether the work was actually useful.',q:'What would count as being seen?'},
   zh:{s:'没人注意到',n:'被看见',g:'你投入了力气的事情就这样过去了，没人提起。',
    p:'下次努力没被提起，你嘴上可能说没关系，但它会一直留着。',
    t:'比起被批评，你可能更难受的是没被注意到。',t1:'被批评',t2:'没有被注意到',
    a:'也可能你想知道的是——这件事到底有没有用。',q:'什么样才算是被看见了？'}},
  certainty:{en:{s:'I couldn’t see ahead',n:'Certainty',g:"You couldn't see what was coming next.",
    p:'Next time something is left open-ended, you may fill in the worst version before any facts arrive.',
    t:'You may handle bad news better than not knowing.',t1:'bad news',t2:'not knowing',
    a:'Or it may be about not being able to prepare.',q:'What could you find out, instead of imagine?'},
   zh:{s:'不知道会怎样',n:'确定性',g:'你看不到接下来会发生什么。',
    p:'下次有事悬着没定，你可能在任何事实出现前，就先把最坏的版本想出来。',
    t:'比起坏消息，你可能更难承受「不知道」。',t1:'坏消息',t2:'「不知道」',
    a:'也可能真正的问题是——你没办法提前准备。',q:'有什么是可以去问清楚，而不是自己想的？'}},
  capacity:{en:{s:'Too much at once',n:'Capacity',g:'Something landed on a plate that was already full.',
    p:'Next time one more thing arrives, you may say yes first and feel the weight afterwards.',
    t:'You may mind the timing of a request more than the request.',t1:'the request itself',t2:'the timing of it',
    a:'Or it may be about how hard it is for you to say no.',q:'What was already on the plate?'},
   zh:{s:'事情太多',n:'负荷',g:'东西压上来的时候，你手上其实已经满了。',
    p:'下次再多一件事，你可能会先答应，之后才感觉到那个重量。',
    t:'比起这件事本身，你可能更在意它来的时机。',t1:'这件事本身',t2:'它来的时机',
    a:'也可能真正难的是——你很不容易说「不」。',q:'在这件事来之前，你手上已经有什么了？'}},
  friction:{en:{s:'I didn’t want to raise it',n:'Friction',g:'You decided not to raise it in the moment.',
    p:'Next time friction shows up, you may let it pass and replay it later instead.',
    t:'You may find the conversation harder than the thing it is about.',t1:'the thing itself',t2:'the conversation about it',
    a:'Or it may be that raising it has cost you before.',q:'What did staying quiet buy you?'},
   zh:{s:'我不想说',n:'摩擦',g:'你在当下选择了不把它说出来。',
    p:'下次再出现摩擦，你可能会先让它过去，然后事后一遍遍回放。',
    t:'比起事情本身，你可能觉得更难的是那场对话。',t1:'事情本身',t2:'那场对话',
    a:'也可能是因为——你以前说出来过，代价不小。',q:'这次不说，帮你换到了什么？'}},
  belonging:{en:{s:'I was left out',n:'Belonging',g:'You were outside something others were inside of.',
    p:'Next time you are left out of something, you may tell yourself it does not matter and check anyway.',
    t:'You may mind being outside more than being overlooked.',t1:'being overlooked',t2:'being left outside',
    a:'Or it may be about not knowing where you stand.',q:'Who did you want to be counted with?'},
   zh:{s:'我被排除在外',n:'归属',g:'别人在里面，而你在外面。',
    p:'下次被排除在外，你可能会告诉自己无所谓，然后还是去看了一眼。',
    t:'比起被忽略，你可能更在意的是被留在外面。',t1:'被忽略',t2:'被留在外面',
    a:'也可能你真正想弄清的是——自己到底算哪一边。',q:'你希望自己被算在谁那一边？'}},
  competence:{en:{s:'My ability was questioned',n:'Competence',g:'Something put your ability in question.',
    p:'Next time your judgement is questioned, you may over-explain before anyone has doubted you.',
    t:'You may mind looking unable more than being wrong.',t1:'being wrong',t2:'looking unable',
    a:'Or it may be about not being trusted to decide.',q:'Who were you proving it to?'},
   zh:{s:'我被质疑了',n:'胜任',g:'有件事让你的能力被打上了问号。',
    p:'下次判断被质疑，你可能会在还没人真的怀疑之前，就先解释一大堆。',
    t:'比起做错，你可能更在意的是显得做不到。',t1:'做错',t2:'显得做不到',
    a:'也可能真正的问题是——没人放心让你来定。',q:'你是在向谁证明？'}}
};
const SIGNAL_KEYS = Object.keys(SIGNALS);

const RESPONSES = {
  react_now:{en:'Reacted right away',zh:'当场就反应了'},
  held_in:  {en:'Held it in',        zh:'忍住没说'},
  paused:   {en:'Paused first',      zh:'先停了一下'},
  talked:   {en:'Talked it through', zh:'把它谈开了'},
  avoided:  {en:'Stepped away',      zh:'避开了'},
  complied: {en:'Went along with it',zh:'顺着做了'},
  other:    {en:'Something else',   zh:'都不是'}
};
/* Words only. These labels are also what the AI backend receives, and with the
   emoji still attached it read them as things the person had typed — it told
   someone they had "shrugged it off with an emoji" when they had tapped a button. */
const REACTIONS = {
  irritated:{en:'Seriously?',      zh:'不是吧？'},
  dread:    {en:'Oh no.',          zh:'完了。'},
  hurt:     {en:'That hurt.',      zh:'有点受伤。'},
  flat:     {en:'Whatever.',       zh:'随便吧。'},
  thinking: {en:'Hmm…',            zh:'让我想想……'},
  ok:       {en:'Actually okay.',  zh:'其实还好。'},
  other:    {en:'Something else',  zh:'都不是'}
};


/* =====================================================================
   KEYWORDS — used only to ORDER the options, never to change their wording.
   Wrong guesses cost nothing: the full list is one tap away.
   ===================================================================== */
const KEYWORDS = {
  autonomy:  ['没问我','没先问','没商量','没说一声','直接就','替我','擅自','临时改','被改','改了我','不由分说','没通知我就',
              'without asking','didn\u2019t ask','decided for me','no say','changed my','over my head','behind my back'],
  heard:     ['没人回','没人听','跳过','打断','不理','忽略','说了两次','没人接','当没听见',
              'interrupted','ignored','skipped','nobody responded','said it twice','talked over'],
  fairness:  ['不公平','凭什么','别人就','双标','偏心','为什么只有我','区别对待',
              'unfair','double standard','favoritism','why do they get','everyone else gets'],
  standards: ['粗糙','不合格','凑合','返工','做得差','质量','敷衍','没做好',
              'sloppy','rushed','below standard','rework','poor quality','half done'],
  valued:    ['没人提','没人注意','白做','没有认可','没人说','当作理所当然','没人看见',
              'unnoticed','no credit','no thanks','unacknowledged','taken for granted'],
  certainty: ['不知道','还没定','悬着','没消息','等消息','不确定','没个说法','会不会',
              'unclear','no news','still waiting','uncertain','up in the air','what if'],
  capacity:  ['又来','太多','忙不过来','还没做完','加班','塞给我','压力','排不过来','手上还有',
              'too much','another one','already full','overloaded','piled on','no bandwidth'],
  friction:  ['忍住','没说出口','不想吵','算了','憋着','回避','没敢说','咽下去',
              'let it go','didn\u2019t say','avoided','held back','didn\u2019t want to argue','bit my tongue'],
  belonging: ['没叫我','没带我','没通知我','排除','只有我不','群里','没有我','局外',
              'left out','not invited','everyone but me','excluded','out of the loop'],
  competence:['质疑','不相信我','不放心','被检查','不信任','怀疑我','觉得我不行',
              'questioned','doubted','didn\u2019t trust me','second-guessed','checked up on me']
};

/* how strong it was — the one thing the signal cannot tell us */
const INTENSITY = {
  light: {en:'It was a flicker',   zh:'只是隐隐的一下',   v:1},
  medium:{en:'It was clearly there',zh:'当时挺明显的',    v:2},
  strong:{en:'It took me over',    zh:'很强，压住我了',   v:3}
};


/* ---------- copy ---------- */
const C = {
 en:{
  notSoMuch:'It may not be',soMuchAs:'so much as',
  gapsTitle:'When the list did not fit',
  gapsNone:'You have not needed "something else" yet.',
  gapsRate:(off,total,pct)=>`${off} of ${total} moments went off-list · ${pct}%`,
  gapsFits:'The list is covering what comes up.',
  gapsGaps:'A few things keep falling outside the list.',
  gapsWrong:'The list is missing something it should have.',
  gapsHint:'These never feed pattern detection. They are here to tell you what the list should have had.',
  gapsField:{reaction:'first reaction',signal:'what got you',response:'what you did'},
  gapsTimes:n=>n===1?'once':n+' times',
  seeGaps:'Review what the list missed',
  brand:'PATTERNA',
  brandLine:'Notice what repeats.\nSee what changes.',
  speaker:'PATTERNA',youChose:'You chose',andAlso:'and',
  weekTitle:'Your week of noticing',
  weekCount:n=>`You captured ${n===1?'1 moment':n+' moments'}.`,
  weekTop:'What came up most',weekReact:'Your most common first reaction',
  weekWrote:'Something you wrote',weekCarry:'One thing to notice next week',
  weekDismiss:'Close',
  nowPicture:'Where you are now',
  thenPending:'Then',thenPendingB:'Not enough history yet',
  unlockCount:n=>`${n} more on this signal`,unlockDays:n=>`about ${n} more days`,
  unlockBoth:(n,d)=>`${n} more on this signal, and about ${d} more days`,
  unlockLead:'To compare, we still need',
  formingNow:'Taking shape',
  formingMix:(name,resp,pct)=>`So far on "${name}", mostly: ${resp} — ${pct}%.`,
  formingWatch:"Give it a little more and you'll see whether it's shifting.",
  unlockFresh:n=>`Start with a few moments. A comparison needs ${n} on the same signal, a few weeks apart.`,
  intensityH:'How strong was it?',
  moreOptions:'Other possibilities',fewerOptions:'Show fewer',
  softerNow:'It does not hit as hard as it used to.',
  sameOften:'It still happens just as often.',
  intThen:'Then',intNow:'Now',
  holdTalk:'Hold to talk',listening:'Listening…',voiceOff:'Voice input is not available in this browser.',
  otherWhat:'Tell us in your own words',otherPh:'What would you call it?',
  followSystem:'Follow device language',
  privacyLine:'Your reflections stay on this device. We do not diagnose you or label you.',
  homeHintSignal:'If the same signal shows up again, we will tell you.',
  exampleTag:'Example',
  exThen:'Reacted right away',exNow:'Paused first',
  obLang:'Choose a language',
  ob1B:'Capture the moments that stick with you. Over time, see what keeps coming back — and whether your response to it is shifting.',
  ob2E:'How this works',ob2H:'This is not a journal.',
  ob2B:"You don't need to write every day. Come back when something happens. Most moments take under a minute.",
  ob3E:"What we won't do",ob3H:'You decide what feels true.',
  ob3B:'We look for things that repeat, and we always show you the evidence. We do not diagnose you, and we never tell you who you are.',
  obPathsE:'Two ways in',obPathsH:'Two kinds of moment, handled differently.',
  obPathsA:'“The ones that snag you” — not heard, no say, unfair. These go into the engine, to show you your reaction patterns.',
  obPathsB:'“The ones that move you” — a film, a line, a good you can’t name. These are only kept and revisited — never analyzed.',
  obStart:'Start',obNext:'Continue',obAgain:'Read the intro again',
  home:'Home',patterns:'Patterns',changes:'Changes',me:'Me',
  somethingHappened:'Something happened?',catchOne:'The ones that snag you',
  nothingYet:'Nothing here yet. Come back when something happens.',
  showingUp:"What's showing up",recent:'Recent moments',noSignals:'Every moment adds a piece.',
  momentsCount:n=>n===1?'1 moment':n+' moments',
  whatHappened:'What happened?',oneSentence:'One sentence is enough.',
  whatPh:'e.g. My manager added another task without asking me first.',
  firstReaction:'Your first reaction?',
  whatGot:'What got you?',closest:'Pick the closest one.',

  whatDid:'What did you do next?',
  next:'Next',save:'Save',done:'Done',skip:'Skip',cancel:'Cancel',back:'Back',
  mirrorH:"Here's what you noticed.",mirrorB:"That's enough for now.",
  mirrorPromise:s=>`We'll hold on to "${s}". If it shows up again, we'll tell you.`,
  mirrorAgain:s=>`"${s}" — here again.`,
  mirrorPromiseOff:"This one isn't on my list — but I've kept it, and it's helping me see what the list is missing.",
  offListWord:'hard to name',
  weekBrightLab:'A bright moment you kept this week',
  weekBrightTitle:'A bright moment this week',
  aiCta:'Have it respond',
  aiThinking:'Reading what you wrote…',
  aiErr:"Couldn't reach it just now — try again in a bit.",
  aiWho:'After reading',
  aiSends:'Reads this moment and a few recent ones — never what you kept.',
  aiSendsNote:'Reads only the line you just wrote.',
  aiCapLeft:n=>`${n} left today`,
  aiCapDone:'That’s all the reflections for today — back tomorrow.',
  letgoLines:['Saved.','Kept.',"It's here now.",'All here.','Okay, kept.','Got it down.'],
  letgoDone:'Set it down',
  seconds:n=>n+' seconds',
  connH:"You've been here before.",
  connB:n=>`That's the ${n===2?'2nd':n===3?'3rd':n+'th'} time this one has come up.`,
  glimpseH:'Something is showing up.',
  glimpseB:(h,o)=>`In ${h} of your last ${o} moments:`,
  tooEarly:"Too early to call this a pattern. But it may be worth watching.",
  yourRead:'What do you think is going on?',yourReadPh:'In your own words…',
  keepWatching:'Keep watching this',probablyNothing:'Probably nothing',
  ourGuess:'Our guess',seeIfRight:"Nothing to do. Just live, and see if we're right.",
  wellSee:"We'll see",
  rememberGuess:'Remember our guess?',wasItTrue:'Was that true this time?',
  yes:'Yes',kindOf:'Kind of',no:'No',
  adjusted:"Good to know. We'll adjust what we're watching.",
  noted:'Noted.',
  possiblePattern:'A possible pattern',confidence:'Confidence',
  basedOn:(h,t)=>`Based on ${h} of ${t} moments you've recorded. Not a conclusion about you.`,
  feelTrue:'Does this feel true?',thatsMe:"That's me",maybe:'Maybe',notReally:'Not really',
  whyWeThink:'Why we think this',otherPossibility:'Another possibility',
  needMore:'We would need more moments to tell these apart.',
  inYourWords:'In your own words',
  noPatternYet:'No pattern yet.',
  noPatternB:n=>`Signals are still collecting. A pattern needs about ${n} moments on the same signal, spread over a few weeks.`,
  changesEmpty:'Your changes will show up here.',
  changesEmptyB:'Later we compare the same kind of trigger across time, and show whether your response to it moved.',
  moreUntil:n=>`${n} more moments on one signal until the first comparison`,
  thenNow:'Then → Now',then:'Then',now:'Now',
  triggerSame:'The trigger did not disappear.',responseChanged:'What changed was you.',
  saveCard:'Develop a photo',
  overDays:(n,d)=>`${n} moments over ${d} days`,
  predAccuracy:'How our guesses did',
  guessesRight:(h,t)=>`${h} of ${t} turned out right`,
  knowingYou:'Getting to know you',
  openGuessLead:n=>n===1?'One open guess':`${n} open guesses`,
  guessPeek:"Peek at what it's guessing",
  guessesTitle:"What it's guessing",
  guessesScoreLead:'How well it knows you',
  guessRejectHelps:'Telling it "no" is what teaches it.',
  guessesIntro:"Now and then it makes a guess, then checks itself. Give it a few and you'll see how well it knows you.",
  openGuessesHead:'Open guesses',
  guessWaiting:"Not settled yet. Next time this happens, we'll know.",
  noOpenGuesses:'No open guesses right now.',
  yourData:'Your data',exportB:'Export everything (JSON)',importB:'Import a backup',
  clearB:'Delete everything',clearConfirm:'Delete every moment permanently? This cannot be undone.',
  storageWarn:'This browser is not saving data between visits. Export before you close the tab.',
  lang:'Language',demoLoad:'Load 90 days of sample data',demoWarn:'This replaces what you have. Export first if you want to keep it.',
  aboutT:'What this is',
  aboutB:'A place to notice what repeats. It does not diagnose you and it is not therapy. Everything stays on this device.',
  del:'Delete this moment',
  noteCta:'The ones that move you',
  noteH:'Something to keep?',
  noteB:'Good, small, hard to name — anything. Just a line.',
  notePh:'Just a line…',
  noteTag:'kept'
 },
 zh:{
  notSoMuch:'你可能不是最在意',soMuchAs:'而是更在意',
  gapsTitle:'词表没接住的东西',
  gapsNone:'你还没有用过「都不是」。',
  gapsRate:(off,total,pct)=>`${total} 次里有 ${off} 次选了「都不是」 · ${pct}%`,
  gapsFits:'词表基本接得住你遇到的事。',
  gapsGaps:'有几类东西反复落在词表之外。',
  gapsWrong:'词表缺了它本该有的东西。',
  gapsHint:'这些内容永远不参与模式判断。它们放在这里，是为了告诉你词表本该有什么。',
  gapsField:{reaction:'第一反应',signal:'哪一点最戳你',response:'然后你做了什么'},
  gapsTimes:n=>n+' 次',
  seeGaps:'看看词表漏了什么',
  brand:'PATTERNA',
  brandLine:'看见重复，\n也看见改变。',
  speaker:'我们注意到',youChose:'你选择了',andAlso:'以及',
  weekTitle:'你这一周的观察',
  weekCount:n=>`你记录了 ${n} 个瞬间。`,
  weekTop:'出现最多的',weekReact:'最常见的第一反应',
  weekWrote:'你写过的一句话',weekCarry:'下周可以留意的一件事',
  weekDismiss:'知道了',
  nowPicture:'现在的你',
  thenPending:'那时',thenPendingB:'历史还不够',
  unlockCount:n=>`这个信号再 ${n} 次`,unlockDays:n=>`大约再 ${n} 天`,
  unlockBoth:(n,d)=>`这个信号再 ${n} 次，以及大约再 ${d} 天`,
  unlockLead:'要做对比，还差',
  formingNow:'正在成形',
  formingMix:(name,resp,pct)=>`目前「${name}」上，你多半「${resp}」——${pct}%。`,
  formingWatch:'等它再攒一些，就能看出你是不是在变。',
  unlockFresh:n=>`先记几个瞬间。做一次对比，需要同一个信号累积 ${n} 次，并且跨过几周。`,
  intensityH:'这次有多强？',
  moreOptions:'其他可能',fewerOptions:'收起来',
  softerNow:'它现在没那么疼了。',
  sameOften:'这件事发生的频率没有变。',
  intThen:'那时',intNow:'现在',
  holdTalk:'按住说话',listening:'在听……',voiceOff:'这个浏览器不支持语音输入。',
  otherWhat:'用你自己的话说说',otherPh:'你会怎么称呼它？',
  followSystem:'跟随系统语言',
  privacyLine:'你的记录只留在这台设备上。我们不诊断你，也不给你贴标签。',
  homeHintSignal:'如果同一个信号再出现，我们会告诉你。',
  exampleTag:'示例',
  exThen:'当场就反应了',exNow:'先停了一下',
  obLang:'选择语言',
  ob1B:'记录那些让你在意的瞬间。慢慢地，看见什么在不断回来——以及你对它的反应，是不是正在变。',
  ob2E:'它怎么用',ob2H:'这不是一本日记。',
  ob2B:'你不用每天写。有事情发生、让你在意的时候，再回来。大部分记录不到一分钟。',
  ob3E:'我们不会做的事',ob3H:'像不像你，由你判断。',
  ob3B:'我们会找那些重复出现的东西，并且永远把依据摆给你看。但我们不诊断你，也不会告诉你「你是谁」。',
  obPathsE:'两条路',obPathsH:'两种瞬间，去处不同。',
  obPathsA:'「被绊到的」——没被听见、没得选、不公平那种。这些进引擎，帮你看出你反应的模式。',
  obPathsB:'「被打动的」——一部电影、一句话、说不清的好。这些只被留住、被回看，永远不分析。',
  obStart:'开始',obNext:'继续',obAgain:'重看一次开场',
  home:'首页',patterns:'模式',changes:'变化',me:'我',
  somethingHappened:'发生了点什么？',catchOne:'被绊到的瞬间',
  nothingYet:'这里还是空的。有事情发生的时候再回来。',
  showingUp:'正在出现的信号',recent:'最近的记录',noSignals:'每一个瞬间，都会多一块拼图。',
  momentsCount:n=>'已记录 '+n+' 个瞬间',
  whatHappened:'发生了什么？',oneSentence:'一句话就够了。',
  whatPh:'例如：我的领导没问我，就又塞给我一个任务。',
  firstReaction:'你的第一反应是？',
  whatGot:'哪一点最戳到你？',closest:'选一个最接近的。',

  whatDid:'然后你做了什么？',
  next:'下一步',save:'保存',done:'完成',skip:'跳过',cancel:'取消',back:'返回',
  mirrorH:'这是你刚刚注意到的。',mirrorB:'今天看到这里就够了。',
  mirrorPromise:s=>`「${s}」我们记下了。如果它再出现，我们会告诉你。`,
  mirrorAgain:s=>`又是「${s}」。`,
  mirrorPromiseOff:'这个不在我的词表里——但我记下了。它在帮我看清词表还缺什么。',
  offListWord:'说不清的那一下',
  weekBrightLab:'这周你也留下过一个亮的时刻',
  weekBrightTitle:'这周，有一个亮的时刻',
  aiCta:'让它回应一句',
  aiThinking:'在读你写的……',
  aiErr:'这会儿没连上——过会儿再试。',
  aiWho:'读完之后',
  aiSends:'会读这一条和最近几条，不含你留住的东西。',
  aiSendsNote:'只读你刚写的这一句。',
  aiCapLeft:n=>`今天还剩 ${n} 次`,
  aiCapDone:'今天的次数用完了——明天再来。',
  letgoLines:['记下了。','收下了。','在这里了。','都在了。','好，收下了。','嗯，记下了。'],
  letgoDone:'放下',
  seconds:n=>n+' 秒',
  connH:'这个地方你来过。',
  connB:n=>`这是它第 ${n} 次出现了。`,
  glimpseH:'好像有点东西正在出现。',
  glimpseB:(h,o)=>`最近 ${o} 次记录里，有 ${h} 次是：`,
  tooEarly:'现在还太早，不能叫它模式。但值得继续看看。',
  yourRead:'你觉得这是怎么回事？',yourReadPh:'用你自己的话说……',
  keepWatching:'继续观察它',probablyNothing:'可能没什么',
  ourGuess:'我们猜一下',seeIfRight:'你什么都不用做。继续生活，然后看看我们猜得准不准。',
  wellSee:'看看吧',
  rememberGuess:'还记得我们上次的猜测吗？',wasItTrue:'这一次是这样吗？',
  yes:'是',kindOf:'有一点',no:'不是',
  adjusted:'收到。我们会调整接下来观察的方向。',
  noted:'记下了。',
  possiblePattern:'一个可能的模式',confidence:'可信度',
  basedOn:(h,t)=>`基于你记录的 ${t} 个瞬间中的 ${h} 个。这不是关于你这个人的结论。`,
  feelTrue:'这个判断像你吗？',thatsMe:'太像了',maybe:'有一点',notReally:'不太对',
  whyWeThink:'我们为什么这么说',otherPossibility:'另一种可能',
  needMore:'要分清这两种，还需要更多记录。',
  inYourWords:'你自己写的',
  noPatternYet:'还没有形成模式。',
  noPatternB:n=>`信号还在累积。一个模式大约需要同一信号出现 ${n} 次，并且跨越几周。`,
  changesEmpty:'你的变化会出现在这里。',
  changesEmptyB:'以后我们会拿同一类触发做跨时间的比较，看看你的回应方式有没有动。',
  moreUntil:n=>`同一个信号再积累 ${n} 次，就能做第一次对比`,
  thenNow:'那时 → 现在',then:'那时',now:'现在',
  triggerSame:'触发你的事情并没有消失。',responseChanged:'变化的是你。',
  saveCard:'洗成一张照片',
  overDays:(n,d)=>`${n} 次记录，横跨 ${d} 天`,
  predAccuracy:'我们猜得怎么样',
  guessesRight:(h,t)=>`${t} 次里猜中了 ${h} 次`,
  knowingYou:'它在慢慢懂你',
  openGuessLead:n=>n===1?'还有一个开着的猜测':`还有 ${n} 个开着的猜测`,
  guessPeek:'点开看看它在猜什么',
  guessesTitle:'它在猜什么',
  guessesScoreLead:'它有多懂你',
  guessRejectHelps:'你说「不是」，反而帮它更懂你。',
  guessesIntro:'它偶尔会押一个猜测，然后自己去验证。攒几次，你就能看出它有多懂你。',
  openGuessesHead:'开着的猜测',
  guessWaiting:'还没揭晓。等下次这种事发生，就知道准不准了。',
  noOpenGuesses:'现在没有开着的猜测。',
  yourData:'你的数据',exportB:'导出全部（JSON）',importB:'导入备份',
  clearB:'删除全部',clearConfirm:'永久删除所有记录？无法撤销。',
  storageWarn:'这个浏览器没有在保存数据。关掉页面前请先导出。',
  lang:'语言',demoLoad:'载入 90 天示范数据',demoWarn:'这会覆盖你现在的记录。想保留请先导出。',
  aboutT:'这是什么',
  aboutB:'一个用来看见重复的地方。它不诊断你，也不是心理治疗。所有数据都留在这台设备上。',
  del:'删除这条记录',
  noteCta:'被打动的瞬间',
  noteH:'想留住点什么？',
  noteB:'好的、小的、说不清的，都行。就一句话。',
  notePh:'就一句话……',
  noteTag:'留了一下'
 }
};

/* =====================================================================
   STORAGE — localStorage when available, memory otherwise, always exportable
   ===================================================================== */
const Store = (() => {
  const KEY = 'kyp.v1';
  let mem = null, ok = true;
  try { localStorage.setItem('kyp.t','1'); localStorage.removeItem('kyp.t'); }
  catch(e){ ok = false; }
  const blank = () => ({moments:[], predictions:[], notes:[], ai:{day:'',used:0}, lang:'zh', onboarded:false, created:Date.now()});
  return {
    persistent: ok,
    load(){
      if(mem) return mem;
      if(ok){ try{ const raw=localStorage.getItem(KEY); mem = raw?JSON.parse(raw):blank(); }catch(e){ mem=blank(); } }
      else mem = blank();
      return mem;
    },
    save(d){ mem=d; if(ok){ try{ localStorage.setItem(KEY, JSON.stringify(d)); }catch(e){} } },
    reset(){ mem=blank(); if(ok){ try{ localStorage.removeItem(KEY); }catch(e){} } return mem; }
  };
})();
